{
 "title": "Foodtrucks",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Applicant",
    "query": {
     "query": "label_values(location_expiration_epoch,Applicant)"
    }
   },
   {
    "name": "Status",
    "query": "select distinct Status from [foodtrucks].[dbo].[mostrecent_raw]"
   },
   {
    "name": "Fooditems",
    "query": "  select distinct ss.value as [fooditems] from [foodtrucks].[dbo].[mostrecent_raw] r\n  cross Apply STRING_SPLIT(r.FoodItems ,':') ss\nwhere Applicant in ($Applicant)\nand Status in ($Status)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard is used to visualize Foodtruck data. See the [source code](https://github.com/brandonmcclure/foodtrucks) for more info."
   }
  },
  {
   "title": "ETL Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time since last run",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() - max(data_data_instance_last_complete_epoch_seconds_diff) by(script_name)",
       "legendFormat": "{{script_name}}"
      }
     ]
    },
    {
     "title": "Textfile error",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      { "expr": "node_textfile_scrape_error", "legendFormat": "{{job}}" }
     ]
    }
   ]
  },
  { "title": "Applicant Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Permits",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "foodtrucks",
     "rawSql": "SELECT TOP(50) COUNT(*) FROM foodtrucks.dbo.mostrecent_raw WHERE Applicant IN ($Applicant) and Status IN ($Status) "
    }
   ]
  },
  {
   "title": "Time to Expiration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min(location_expiration_epoch{Applicant=~\"$Applicant\"}) by (Applicant) - time()",
     "legendFormat": "{{Applicant}}"
    }
   ]
  },
  {
   "title": "Location Map",
   "type": "geomap",
   "description": "Colors indicate the Permit status",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "dataset": "foodtrucks",
     "rawSql": "SELECT TOP(100) locationid,Latitude, Longitude, Applicant, FacilityType, Status, FoodItems,\r\ncase when Status in ('APPROVED','ISSUED') then 1 \r\nwhen Status in ('REQUESTED','ONLINE') then 2\r\nwhen Status in ('EXPIRED','SUSPEND') then 3\r\nelse 0 END as [Status_int] \r\nFROM foodtrucks.dbo.mostrecent_raw r\r\ncross Apply STRING_SPLIT(r.FoodItems ,':') ss\r\nWHERE Applicant IN ($Applicant) AND Latitude <> '0' and Longitude <> '0'\r\nand Status in ($Status)\r\nand ss.Value in ($Fooditems)"
    }
   ]
  },
  {
   "title": "Raw Data",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT TOP(100) locationid, Applicant, FacilityType, LocationDescription,Address, permit, status, fooditems, schedule, Approved, ExpirationDate\r\nFROM foodtrucks.dbo.mostrecent_raw r\r\n  cross Apply STRING_SPLIT(r.FoodItems ,':') ss\r\nWHERE Applicant IN ($Applicant) AND Latitude <> '0' and Longitude <> '0'\r\nand Status in ($Status)\r\nand ss.Value in ($Fooditems)"
    }
   ]
  }
 ]
}